name: deploy

on:
  push:
    branches: [ master ]

jobs:

  deploy:
    name: Upload Layer to AWS Lambda
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # For more info: https://github.com/aws-actions/configure-aws-credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15
        id: go

      - name: Set up cache for Go dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get Go Dependencies
        run: |
          echo "$(go env GOPATH)/bin" >> "${GITHUB_PATH}"
          go get -v -u ./...

      - name: Build go files
        run: make build
        
      - name: Serverless
        uses: serverless/github-action@v1.53.0
        with:
          args: deploy
